# Change these first
owner: pbs-itsupport # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: IT Glue
    url: https://pbs.itglue.com
  - name: N-Able
    url: https://rescue.pbscompany.com
  - name: Gmail
    url: https://accounts.google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org

  #General Settings
  baseUrl: /upptime
  theme: night
  logoUrl: https://raw.githubusercontent.com/pbs-itsupport/upptime/6accfa93c903accb6b9de4b94f803b0988f3489b/assets/whitesquare.png
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PBS Status Monitor
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
